# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
default:
    - override hydra/launcher: local
    - override hydra/output: local

# general inputs
env               :   drawer-open-v2-goal-observable 
pixel_based       :   True                    # pixel based (True) or state based (False) experiment
embedding         :   resnet50                # choice of embedding network
camera            :   left_cap2            # choice of camera to use for image generation
device            :   cuda

# experiment and evaluation
seed              :   123                     # used as base_seed for rolling out policy for eval in sample_paths
steps             :   20000                  # number of outer epochs
eval_frequency    :   1000                       # frequency of epochs for evaluation and logging
eval_num_traj     :   5                      # number of rollouts to eval
num_cpu           :   1                       # for rolling out paths when evaluating                 
num_demos         :   25                     # path to demo file auto-inferred from other inputs
proprio           :   0

# environment related kwargs
env_kwargs:
    env_name      :   drawer-open-v2-goal-observable               
    device        :   cuda               # device to use for representation network (policy clamped to CPU for now)
    image_width   :   256
    image_height  :   256
    camera_name   :   left_cap2
    embedding_name :  resnet50                
    pixel_based   :   True
    render_gpu_id :   0                 
    load_path     :   r3m  
    proprio       :   4 
    lang_cond     :   False
    gc            :   False

# demo reparsing arguments (states -> image embeddings)
reparse_kwargs:
    visualize     :   True                   # store videos (.mp4) of the trajectory while reparsing
    save_frames   :   True                   # save the generated images in the trajectory (can increase storage space dramatically)

# BC agent setup
bc_kwargs:
  loss_type       :   'MSE'
  batch_size      :   32 #200
  lr              :   1e-3
  save_logs       :   False
  finetune        :   False
  proprio         :   4  
  proprio_only    :   False

# general outputs
job_name          :   'R3M'

hydra:
    job:
        name: BC_pretrained_rep
